# Generated by Django 4.2.20 on 2025-03-30 11:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_month', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('pdf', models.FileField(upload_to='uploads/reports/')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='residents.resident')),
            ],
        ),
    ]
