# Generated by Django 4.2.13 on 2024-07-20 09:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associates', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_month', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('pdf', models.FileField(upload_to='uploads/reports/')),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='associates.associates')),
            ],
        ),
    ]
