# Generated by Django 4.2.20 on 2025-04-10 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0002_rename_session_therapysession'),
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='therapy_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='therapy_sessions.therapysession'),
        ),
    ]
