# Generated by Django 4.2.20 on 2025-04-10 09:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_video_therapy_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EmotionAnalysisSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('angry_avg', models.FloatField(default=0.0)),
                ('disgust_avg', models.FloatField(default=0.0)),
                ('fear_avg', models.FloatField(default=0.0)),
                ('happy_avg', models.FloatField(default=0.0)),
                ('neutral_avg', models.FloatField(default=0.0)),
                ('sad_avg', models.FloatField(default=0.0)),
                ('surprised_avg', models.FloatField(default=0.0)),
                ('dominant_emotion', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_summary', to='analysis.video')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(help_text='Timestamp in seconds from the start of the video')),
                ('angry', models.FloatField(default=0.0)),
                ('disgust', models.FloatField(default=0.0)),
                ('fear', models.FloatField(default=0.0)),
                ('happy', models.FloatField(default=0.0)),
                ('neutral', models.FloatField(default=0.0)),
                ('sad', models.FloatField(default=0.0)),
                ('surprised', models.FloatField(default=0.0)),
                ('dominant_emotion', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_analyses', to='analysis.video')),
            ],
            options={
                'ordering': ['video', 'timestamp'],
            },
        ),
    ]
