# Generated by Django 4.2.20 on 2025-04-10 13:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_video_status_emotionanalysissummary_emotionanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionanalysissummary',
            name='emotion_counts',
            field=models.JSONField(default=dict, help_text='Count of frames for each emotion'),
        ),
        migrations.CreateModel(
            name='EmotionTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.FloatField(help_text='Start time in seconds from the start of the video')),
                ('end_time', models.FloatField(help_text='End time in seconds from the start of the video')),
                ('duration', models.FloatField(help_text='Duration of this emotion segment in seconds')),
                ('dominant_emotion', models.CharField(max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score for this emotion segment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_timeline', to='analysis.video')),
            ],
            options={
                'ordering': ['video', 'start_time'],
            },
        ),
    ]
