# Generated by Django 4.2.20 on 2025-04-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
        ('feedbacks', '0001_initial'),
        ('therapy_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='TherapySession',
        ),
    ]
